# fetch and post RSS articles
name: feeds

on:
  schedule:
    - cron: "0 15 * * *" # 15:00 UTC / 7am PDT /8 am PST
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: >
        node feeds.js
        --email    "${{secrets.EMAIL}}"
        --password "${{secrets.PASSWORD}}"
        --key      "${{secrets.KEY}}"
        --imgbb    "${{secrets.IMGBB}}"
