# This is a basic workflow to help you get started with Actions

name: Fetch

on:
  schedule:
    - cron: "0 15 * * *" # 15:00 UTC / 7am PDT /8 am PST

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  execute:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: node index.js
