# fetch and post RSS articles
name: fetch

on:
  schedule:
    - cron: "0 15 * * *" # 15:00 UTC / 7am PDT /8 am PST
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - id: install packages
      run: npm install
      
    - id: run
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
    - run: node index.js --trace-warnings
