# This is a basic workflow to help you get started with Actions

name: Fetch

on:
  schedule:
    - cron: "0 15 * * *" # 15:00 UTC / 7am PDT /8 am PST
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: node index.js
